### ISSUE TITLE
Unsafe build flags

### ISSUE THREAD

**Issue by rarias84** [taji-taji/DangerSwiftPeriphery#55]
Using any version I receive 
error: the target 'PeripheryKit' in product 'periphery' contains unsafe build flags
error: the target 'PeripheryKit' in product 'DangerSwiftPeriphery' contains unsafe build flags

.package(url: "https://github.com/taji-taji/DangerSwiftPeriphery.git", from: "1.3.0")
.product(name: "DangerSwiftPeriphery", package: "DangerSwiftPeriphery")

**Comment by rarias84** [comment]
any solution?

**Comment by taji-taji** [comment]
@rarias84 
Sorry for the late reply.
It seems to be fixed in periphery 2.10.3, so I will change this library to update as well.

**Comment by taji-taji** [comment]
This is fixed in [1.3.1](https://github.com/taji-taji/DangerSwiftPeriphery/releases/tag/1.3.1).
