### ISSUE TITLE
DangerSwiftPeriphery doesn't work in macos13.0

### ISSUE THREAD

**Issue by rarias84** [taji-taji/DangerSwiftPeriphery#62]
Running the last version:

error: the library 'DangerSwiftPeriphery' requires macos 12.0, but depends on the product 'periphery' which requires macos 13.0; consider changing the library 'DangerSwiftPeriphery' to require macos 13.0 or later, or the product 'periphery' to require macos 12.0 or earlier.

**Comment by taji-taji** [comment]
Thanks for the report!
DangerSwiftPeriphery requires macOS 13 or later starting with v1.3.3.
